[tool.poetry]
name = "pulumi-cloud-client"
version = "0.1.0"
description = ""
authors = ["Richard Shade <richard@pulumi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
