name: Python Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality and Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for commit message validation

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.5.1'
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Check formatting with Black
      run: |
        poetry run black --check .

    - name: Lint with flake8
      run: |
        poetry run flake8 .

    - name: Sort imports check
      run: |
        poetry run isort --check .

    - name: Type check with mypy
      run: |
        poetry run mypy pulumi_cloud_client tests

    - name: Run tests
      run: |
        poetry run test -v

    - name: Validate commit messages
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        # Make sure commitizen is available and then run it
        poetry run pip install commitizen
        poetry run python -m commitizen check --rev-range origin/${{ github.base_ref }}..HEAD
